Repository Moises-Giron/Coffee-Review, pull requests merged in 2022-02, with the labels that each got.

#5 Fixes user creation upon logging in with Google oauth
  config/passport.js
  model/index.js
  routes/auth.js
Labels: bug

#9 Inserts Video Underneath Navigation Menu
  public/css/styles.css
  public/index.html
  views/index.ejs
  views/index.js
Labels: enhancement

#15 Integrates OAuth to Navigation UI
  controller/home.js
  controller/products.js
  server.js
  views/partials/nav.ejs
Labels: enhancement

#17 Finishes Homepage Setup
  public/css/styles.css
  views/home.ejs
  views/partials/nav.ejs
Labels: enhancement

#18 Dbproduct
  public/css/styles.css
  views/products/index.ejs
Labels: documentation

#19 Inserting background image at the end of the home page
  public/images/beansOnTable.jpg
Labels: enhancement

#20 Product update
  .gitignore
  public/css/styles.css
  test.txt
  views/partials/footer.ejs
  views/products/index.ejs
Labels: enhancement

#21 changed review button to point to ID and not Name
  views/products/index.ejs
Labels: enhancement

#22 Update home
  public/css/styles.css
  views/home.ejs
Labels: enhancement

#23 Provides product and review information
  controller/reviews.js
  model/index.js
  model/products.js
  model/reviews.js
  routes/reviews.js
  server.js
  views/home.ejs
  views/products/reviews.ejs
  views/products/singleReview.ejs
Labels: enhancement

#24 Delete
  controller/reviews.js
  package-lock.json
  package.json
  routes/reviews.js
  server.js
  views/products/singleReview.ejs
Labels: enhancement

#25 Provides update functionality to reviews
  controller/reviews.js
  routes/reviews.js
  server.js
  views/products/singleReview.ejs
  views/products/updateReviews.ejs
Labels: enhancement

#27 Removed duplicate code and fixed syntax issues
  controller/reviews.js
  views/products/singleReview.ejs
Labels: bug

#30 Adds verification that user is logged in
  controller/reviews.js
  routes/reviews.js
  views/products/singleReview.ejs
Labels: enhancement

#31 Adds user validation to reviews
  views/products/singleReview.ejs
  views/products/updateReviews.ejs
Labels: enhancement

#32 Centers and fixes spacing issues with flex and removes a heading
  public/css/styles.css
  views/products/singleReview.ejs
Labels: bug

#33 Update css
  views/partials/header.ejs
  views/products/index.ejs
  views/products/singleReview.ejs
  views/products/updateReviews.ejs
Labels: enhancement

#36 Title position fix for main page
  public/css/styles.css
Labels: bug
